spring:
  #生产环境
  profiles:
    active: prod

  #连接数据库
  datasource:
    url: jdbc:mysql://47.96.114.93:3306/heriecblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone = GMT
    username: root
    password: "0814"
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat,wall  # 配置底层功能，sql监控和防火墙
      # 详细配置stat
      filter:
        stat:
          slow-sql-millis: 1000 #定义一秒以上的为慢SQL
          db-type: mysql
          log-slow-sql: true # 记录慢SQL
        wall:
          config:
          #            drop-table-allow: false # 拦截所有删表方法
          db-type: mysql
          enabled: true #防止SQL注入问题

      #配置监控页面
      stat-view-servlet:
        enabled: true   # 开启监控页
        #        login-username: admin
        #        login-password: admin
        allow:
        deny:

      # 配置监控web
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'


  redis:
    host: 47.96.114.93
  #  host: localhost
    port: 6379
    password: "0814"

# 配置mybatis-plus
mybatis-plus:
  configuration:
    # 是否开启自动驼峰命名规则（camel case）映射，即从经典数据库列名 A_COLUMN（下划线命名） 到经典 Java 属性名 aColumn（驼峰命名） 的类似映射
    map-underscore-to-camel-case: true
  type-aliases-package: com.heriec.blogmaster

# 配置七牛云（变量）
oss:
  qiniu:
    domain: r2nvlp5zo.hn-bkt.clouddn.com  # 七牛云外链域名
    prefix: blog # 前缀,相当于项目路径
    accessKey: _5yK1ENKgR8jKgrk-9uLT22Iqa-u2-y2NnVS36L5  # 配置AccessKey（非明文）
    secretKey: PzfGsOIzQai7SzelksYS4CVxJdWuaMB5gCWADLAF  # 配置SecretKey（非明文）
    bucketName: heriecblog # 配置空间名


#token配置
blog:
  jwt:
    # 加密秘钥
    secret: zrf5202e34348f86b67cde581c0f9eb5
    # token有效时长，7天，单位秒
    expire: 604800
    header: token